### ISSUE TITLE
Broken with supertest?

### ISSUE THREAD

**Issue by MichaelJCole** [TooTallNate/superagent-proxy#13]
```
var supertest = require('supertest');
require('superagent-proxy')(supertest);    <-- Here
```
results in:
```
/home/michael/scm/clustermeter/node_modules/superagent-proxy/index.js:97
  if (desc.get == getUrl && desc.set == setUrl) return; // already patched
          ^
TypeError: Cannot read property 'get' of undefined
    at setupUrl (/home/michael/scm/clustermeter/node_modules/superagent-proxy/index.js:97:11)
    at Function.proxy (/home/michael/scm/clustermeter/node_modules/superagent-proxy/index.js:68:3)
    at setup (/home/michael/scm/clustermeter/node_modules/superagent-proxy/index.js:50:18)
    at Object.<anonymous> (/home/michael/scm/clustermeter/app.e2e.js:4:28)    <--- here
    at Module._compile (module.js:460:26)
```
Versions installed:
```
├── superagent@0.21.0
├── superagent-proxy@0.3.1
└── supertest@0.15.0
```

If I uninstall and reinstall, I get this:
```
 npm --save install superagent superagent-proxy supertest
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "node" "/home/michael/.nvm/versions/v0.12.0/bin/npm" "--save" "install" "superagent" "superagent-proxy" "supertest"
npm ERR! node v0.12.0
npm ERR! npm  v2.6.0
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package superagent does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer superagent-proxy@0.3.1 wants superagent@>= 0.15.4 && < 1

npm ERR! Please include the following file with any support request:
npm ERR!     /home/michael/scm/clustermeter/npm-debug.log
```

**Comment by TooTallNate** [comment]
Can you try again with v0.3.2 please?

**Comment by saimanoj01** [comment]
@TooTallNate Do you have any update on this issue?
I am still seeing this even with the latest version.

**Comment by againer** [comment]
Same here; ping @TooTallNate. 
```
The package superagent@0.21.0 does not satisfy its siblings' peerDependencies requirements!
Peer superagent-proxy@0.3.2 wants superagent@>= 0.15.4 && < 2
Peer superagent-retry@0.4.0 wants superagent@~0.19.0
```

**Comment by TooTallNate** [comment]
It works for me:

```
$ npm --save install superagent superagent-proxy supertest
$ ❯ npm ls --depth=0
/Users/nrajlich/test
├── superagent@1.7.0
├── superagent-proxy@1.0.0
└── supertest@1.1.0
```

You might be using an old version of npm, or you need to update your `superagent`/`superagent-proxy`/`supertest` to their latest versions as well.

**Comment by MichaelJCole** [comment]
@TooTallNate hey, sorry I never got back to you on this.  The original issue was for node 0.10.x.  Feel free to close this when you feel it's ready.  Thanks!

**Comment by jakubka** [comment]
I am still getting the issue from the original post.

```
C:\Users\jakub\projects\api-tester\node_modules\superagent-proxy\index.js:92
  if (desc.get == getUrl && desc.set == setUrl) return; // already patched
          ^
TypeError: Cannot read property 'get' of undefined
    at setupUrl (C:\Users\jkadlubi\projects\nextgen-server\api-tester\node_modules\superagent-proxy\index.js:92:11)
    at Function.proxy (C:\Users\jakub\projects\api-tester\node_modules\superagent-proxy\index.js:68:3)
...
```

That's the code which I am using:

```
var request = require('supertest');
require('superagent-proxy')(request); // this produces the error above
```

I am a little bit lost in the thread, as it deals with two issues (this one and installation). Is the above error supposed to be fixed?

Installed packages:

```
superagent@1.7.2
supertest@1.2.0
superagent-proxy@1.0.0
supertest-as-promised@3.0.0
```

Thanks!

**Comment by saimanoj01** [comment]
@jakubka 
`var request = require('supertest-as-promised');
require('superagent-proxy')(request);`

The above code snippet was giving me an error too when using **supertest-as-promised**. I got it working in another way.

`var proxy = require('superagent-proxy');
 var request =  require('supertest-as-promised')(_serverUri_);
 request = .request.get(_resource_);
 proxy(request, _proxyUri_);
 .
 .
 .
 .
`

You can now use the **proxied** request object to make rest calls.
Hope this helps!
