### ISSUE TITLE
Proxy timeouts

### ISSUE THREAD

**Issue by aleksandarkok** [TooTallNate/superagent-proxy#29]
Hi,
this is my request, it works without  .proxy(proxy), but with it timeouts. I have tried several proxy IPs.

const request = require('superagent');
require('superagent-proxy')(request);

let proxy = 'http://217.9.91.39:8080';

request
         .post('https://xxx.net/')
         .proxy(proxy)
         .timeout(1000)
         .set('Access-Control-Allow-Origin', '*')
         .type('form')
         .set('Accept-Language', 'SRB')
         .set('Authorization', 'xxxxxxxxxxxxxxxxxx')
         .send('code='+kod)
         .end((err, res) => {
                    if (err) {
                        console.log('ERR',err);
                    } else {
                        console.log(res.status, res.headers);
                        console.log(res.body);
                    }
         });

 { Error: Timeout of 1000ms exceeded
    at RequestBase._timeoutError (C:\Users\akokanovic\Documents\NetBeansProjects\NodeJS\NodeJsApplication\node_modules\superagent\lib\request-base.js:670:13)
    at Timeout.<anonymous> (C:\Users\akokanovic\Documents\NetBeansProjects\NodeJS\NodeJsApplication\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  timeout: 1000,
  code: 'ECONNABORTED',
  errno: 'ETIME',
  response: undefined }

**Comment by zpzxgcr** [comment]
+1
